version: '2'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=my_sql_A
    ports:
      - '3306:3306'
